target-version = "py312"

[lint]
select = [
  "E4", "E7", "E9",  
  "F",                
  "I",                
  "B",                
  "A",                
  "C4",               
  "S",              
]

ignore = []

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.per-file-ignores]
"tests/*" = ["S101"]
