#!/bin/bash

set -e -o pipefail

flags=()
detailed=false
for arg in "$@"; do
    case "$arg" in
        --detailed) detailed=true ;;
        --*) flags+=("$arg") ;;
    esac
done


if git diff --cached --quiet; then
    echo "Индекс пуст. Нечего коммитить."
    exit 0
else
    echo "Есть изменения в индексе. Генерируем коммит."

    diff=$(git diff --cached)

    if [[ "$detailed" == "true" ]]; then
        commit_message=$(echo "$diff" | python3 "$(dirname "$0")/../generator.py" --detailed)
    else
        commit_message=$(echo "$diff" | python3 "$(dirname "$0")/../generator.py")
    fi

    tmpfile=$(mktemp)
    echo "$commit_message" > "$tmpfile"

    echo -e "Коммит:\n----------------------\n$commit_message\n----------------------"
    echo $detailed
    if [[ "$detailed" == "true" ]]; then
        git commit -m "$title" -m "$body" "${flags[@]}"
        echo "git commit -m "$title" -m "$body" "${flags[@]}""
    else
        git commit -m "$title" "${flags[@]}"
    fi 

    rm "$tmpfile"
fi
