#!/bin/bash

set -e -o pipefail

remotes=($(git remote))
remote_count=${#remotes[@]}

if [ "$remote_count" -eq 0 ]; then
    echo "Нет настроенных удаленных репозиториев (remotes)."
    exit 0
elif [ "$remote_count" -eq 1 ]; then 
    remote=${remotes[0]}
    echo "Используется remote: $remote"
else 
    echo "Найдено несколько remotes:"
    for i in "${!remotes[@]}"; do 
        echo "$((i + 1)) ${remotes[$i]}" 
    done

    while true; do
        read -p "Выберите номер remote для push: " index
        if [[ "$index" =~ ^[0-9]+$ ]] && [ "$index" -ge 1 ] && [ "$index" -le "$remote_count" ]; then
            remote=${remotes[$((index - 1))]}
            echo "Выбран remote: $remote"
            break
        else
            echo "Неверный ввод"
        fi
    done
fi

default_branch=$(git remote show "$remote" | grep 'HEAD branch' | awk '{print $NF}')

flags=()

user_remote=""
branch=""

for arg in "$@"; do
    if [[ "$arg" == --* ]]; then
        flags+=("$arg")
    elif [ -z "$user_remote" ]; then
        user_remote="$arg"
    elif [ -z "$branch" ]; then
        branch="$arg"
    fi
done

if [ -n "$user_remote" ]; then
    remote="$user_remote"
fi

if [ -z "$branch" ]; then
    read -p "Введите имя ветки для push [по умолчанию: $default_branch]: " input_branch
    if [ -z "$input_branch" ]; then
        branch="$default_branch"
        echo "Ветка не указана. Используем: $branch"
    else
        branch="$input_branch"
        echo "Используем ветку: $branch"
    fi
else
    echo "Используем ветку: $branch"
fi

git push "$remote" "$branch" "${flags[@]}"
